/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectotienda;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sirias Cano
 */
public class frmSistemaTienda extends javax.swing.JFrame {

    /**
     * Creates new form frmSistemaTienda
     */
    public frmSistemaTienda() {
        initComponents();
        this.tabledetalles.setModel(modelo);
        this.modelo.addColumn("NACIONALIDAD");
        this.modelo.addColumn("GÉNERO");
        this.modelo.addColumn("TALLAS");
        this.modelo.addColumn("PRENDAS");
        this.modelo.addColumn("CANTIDAD");
        this.modelo.addColumn("PRECIO");
        this.modelo.addColumn("PRECIO UNITARIO");
        this.modelo.addColumn("TOTAL A PAGAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbonacionalidad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        botonh = new javax.swing.JRadioButton();
        botonm = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbotallas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtprenda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btngenerar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledetalles = new javax.swing.JTable();
        btnlimpiartabla = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();
        btnnetopagar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtnetopagar = new javax.swing.JTextField();
        btnReport = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sistema Tienda de Ropa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descuentos o Promociones"));

        jLabel2.setText("Nacional");

        jLabel3.setText("HOMBRE TALLA: S=10% M=10% L=12% XL=14% ");

        jLabel4.setText("MUJER TALLA: S=7% M=7% L=12% XL=14%");

        jLabel5.setText("Extranjeros");

        jLabel6.setText("HOMBRE TALLA: S=7% M=7% L=10% XL=12%");

        jLabel7.setText("MUJER TALLA: S=5% M=5% L=7% XL=10%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Realizar Compra"));

        jLabel8.setText("Nacionalidad:");

        cbonacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Nicaraguense", "Extranjero" }));

        jLabel9.setText("Género:");

        buttonGroup1.add(botonh);
        botonh.setText("Hombre");
        botonh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonhActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonm);
        botonm.setText("Mujer");

        jLabel10.setText("Tallas:");

        cbotallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "S", "M", "L", "XL" }));

        jLabel11.setText("Prenda:");

        txtprenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprendaActionPerformed(evt);
            }
        });

        jLabel12.setText("Cantidad:");

        jLabel13.setText("Precio:");

        jLabel14.setText("Total a Pagar:");

        btngenerar.setText("Generar Compra");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel9)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel10)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btngenerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnlimpiar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbonacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonh)
                    .addComponent(botonm)
                    .addComponent(cbotallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btngenerar)
                            .addComponent(btnlimpiar))
                        .addContainerGap())))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Compras"));

        tabledetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabledetalles);

        btnlimpiartabla.setText("Limpiar Tabla");
        btnlimpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartablaActionPerformed(evt);
            }
        });

        btnquitar.setText("Quitar Compra");
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });

        btnnetopagar.setText("Neto a Pagar");
        btnnetopagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnetopagarActionPerformed(evt);
            }
        });

        jLabel15.setText("Neto a Pagar C$");

        btnReport.setText("Reporte");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnlimpiartabla, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnquitar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiartabla)
                    .addComponent(btnquitar)
                    .addComponent(jLabel15)
                    .addComponent(txtnetopagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport)
                    .addComponent(btnnetopagar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(992, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo = new DefaultTableModel();
    private void botonhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonhActionPerformed

    private void txtprendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprendaActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        this.cbonacionalidad.setSelectedIndex(0);
        if(botonh.isSelected()){
            
        }
        if(botonm.isSelected()){
            
        }
        this.cbotallas.setSelectedIndex(0);
        this.txtcantidad.setText("");
        this.txtprecio.setText("");
        this.txttotal.setText("");
        this.txtprenda.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        descuentos_hombres_extrangeros();
        descuentos_hombres_nacionales();
        descuentos_mujeres_extrangeras();
        descuentos_mujeres_nacionales();
        
        if(botonh.isSelected()){
            this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedItem(),"Hombre", 
            this.cbotallas.getSelectedItem(), this.txtprenda.getText(), this.txtcantidad.getText(),
            this.txtprecio.getText(), this.txttotal.getText()});        
        }
        else if(botonm.isSelected()){
            this.modelo.addRow(new Object[]{this.cbonacionalidad.getSelectedItem(),"Mujer", 
            this.cbotallas.getSelectedItem(), this.txtprenda.getText(), this.txtcantidad.getText(),
            this.txtprecio.getText(), this.txttotal.getText()}); 
        }
    }//GEN-LAST:event_btngenerarActionPerformed

    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
        modelo.removeRow(this.tabledetalles.getSelectedRow());
    }//GEN-LAST:event_btnquitarActionPerformed

    private void btnlimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartablaActionPerformed
        int x = this.modelo.getRowCount();
        for(int y = 0; y<=x; y++){
            this.modelo.removeRow(0);
        }
        this.txtnetopagar.setText("");
    }//GEN-LAST:event_btnlimpiartablaActionPerformed

    private void btnnetopagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnetopagarActionPerformed
       double sumatoria;
       double sumatorial = 0;
       int totalrow = tabledetalles.getRowCount();
       totalrow-=1;
       for(int i=0; i<=(totalrow);i++){
           sumatoria = Double. parseDouble(String.valueOf(tabledetalles.getValueAt(i, 6)));
           sumatorial += sumatoria;
       }
       txtnetopagar.setText("C$"+String.valueOf(sumatorial));
    }//GEN-LAST:event_btnnetopagarActionPerformed
    public void descuentos_hombres_extrangeros(){
        double cantidad_s, precio_s, total_s, desc_s = 0.07;
        double cantidad_m, precio_m, total_m, desc_m = 0.07; 
        double cantidad_l, precio_l, total_l, desc_l = 0.10;
        double cantidad_xl, precio_xl, total_xl, desc_xl = 0.12;
        
        //SI SELECCIONA S
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 1){
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s) - ((cantidad_s * precio_s)*desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
            //SI SELECCIONA M
            if(cbonacionalidad.getSelectedIndex() == 2){
                if(this.botonh.isSelected()){
                    if(cbotallas.getSelectedIndex()==2){
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m) - ((cantidad_m * precio_m)*desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                    }
                }
            }
            //SI SELECCIONA L
            if(cbonacionalidad.getSelectedIndex() == 2){
                if(this.botonh.isSelected()){
                    if(cbotallas.getSelectedIndex()==3){
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l) - ((cantidad_l * precio_l)*desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                    }
                }
            }
            //SI SELECCIONA XL
            if(cbonacionalidad.getSelectedIndex() == 2){
                if(this.botonh.isSelected()){
                    if(cbotallas.getSelectedIndex()==4){
                    cantidad_xl = Double.parseDouble(this.txtcantidad.getText());
                    precio_xl = Double.parseDouble(this.txtprecio.getText());
                    total_xl = (precio_xl * cantidad_xl) - ((cantidad_xl * precio_xl)*desc_xl);
                    this.txttotal.setText(String.valueOf(total_xl));
                    }
                }
            }
            
        }
       
    }
    public void descuentos_mujeres_extrangeras(){
        double cantidad_s, precio_s, total_s, desc_s = 0.05;
        double cantidad_m, precio_m, total_m, desc_m = 0.05; 
        double cantidad_l, precio_l, total_l, desc_l = 0.07;
        double cantidad_xl, precio_xl, total_xl, desc_xl = 0.10;
        
        //SI SE SELECCIONA S
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 1){
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s)-((cantidad_s * precio_s)*desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SI SELECCIONA M
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 2){
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m)-((cantidad_m * precio_m)*desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SI SELECCIONA L
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 3){
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l)-((cantidad_l * precio_l)*desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
        }
        //TALLA XL
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 4){
                    cantidad_xl = Double.parseDouble(this.txtcantidad.getText());
                    precio_xl = Double.parseDouble(this.txtprecio.getText());
                    total_xl = (precio_xl * cantidad_xl)-((cantidad_xl * precio_xl)*desc_xl);
                    this.txttotal.setText(String.valueOf(total_xl));
                }
            }
        }
        
    }
    public void descuentos_mujeres_nacionales(){
        double cantidad_s, precio_s, total_s, desc_s = 0.07;
        double cantidad_m, precio_m, total_m, desc_m = 0.07;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        double cantidad_xl, precio_xl, total_xl, desc_xl = 0.14;
        
        //SI SE SELECCIONA S
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 1){
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s)-((cantidad_s * precio_s)*desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SI SE SELECCIONA M
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 2){
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m)-((cantidad_m * precio_m)*desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SI SE SELECCIONA L
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 3){
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l)-((cantidad_l * precio_l)*desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
        }
        //SI SE SELECCIONA XL
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonm.isSelected()){
                if(cbotallas.getSelectedIndex() == 4){
                    cantidad_xl = Double.parseDouble(this.txtcantidad.getText());
                    precio_xl = Double.parseDouble(this.txtprecio.getText());
                    total_xl = (precio_xl * cantidad_xl)-((cantidad_xl * precio_xl)*desc_xl);
                    this.txttotal.setText(String.valueOf(total_xl));
                }
            }
        }
    }
    public void descuentos_hombres_nacionales(){
        double cantidad_s, precio_s, total_s, desc_s = 0.10;
        double cantidad_m, precio_m, total_m, desc_m = 0.10;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        double cantidad_xl, precio_xl, total_xl, desc_xl = 0.14;
        
        //SI SE SELECCIONA S
        if(cbonacionalidad.getSelectedIndex() == 1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 1){
                    cantidad_s = Double.parseDouble(this.txtcantidad.getText());
                    precio_s = Double.parseDouble(this.txtprecio.getText());
                    total_s = (precio_s * cantidad_s)-((cantidad_s * precio_s)*desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
        
        //SI SE SELECCIONA M
        if(cbonacionalidad.getSelectedIndex() == 1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 2){
                    cantidad_m = Double.parseDouble(this.txtcantidad.getText());
                    precio_m = Double.parseDouble(this.txtprecio.getText());
                    total_m = (precio_m * cantidad_m)-((cantidad_m * precio_m)*desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
         }
        //SI SE SELECCIONA L
        if(cbonacionalidad.getSelectedIndex() == 1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 3){
                    cantidad_l = Double.parseDouble(this.txtcantidad.getText());
                    precio_l = Double.parseDouble(this.txtprecio.getText());
                    total_l = (precio_l * cantidad_l)-((cantidad_l * precio_l)*desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
         }
        //SI SE SELECCIONA XL
        if(cbonacionalidad.getSelectedIndex() == 1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex() == 4){
                    cantidad_xl = Double.parseDouble(this.txtcantidad.getText());
                    precio_xl = Double.parseDouble(this.txtprecio.getText());
                    total_xl = (precio_xl * cantidad_xl)-((cantidad_xl * precio_xl)*desc_xl);
                    this.txttotal.setText(String.valueOf(total_xl));
                }
            }
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSistemaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSistemaTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonh;
    private javax.swing.JRadioButton botonm;
    private javax.swing.JToggleButton btnReport;
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnlimpiartabla;
    private javax.swing.JButton btnnetopagar;
    private javax.swing.JButton btnquitar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbonacionalidad;
    private javax.swing.JComboBox<String> cbotallas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabledetalles;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnetopagar;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprenda;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
